version: '3'
services:

  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
      
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '3080:3080'
    volumes:
      - /app/node_modules
      - ./api:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - web
      - api

